# cloudbuild.yaml
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/VITE_GEMINI_API_KEY/versions/latest
    env: VITE_GEMINI_API_KEY

substitutions:
  _REGION: "us-south1"
  _REPO: "cloud-run-source-deploy"
  _IMAGE_NAME: "meowtion-sensor"

steps:
- name: gcr.io/cloud-builders/docker
  secretEnv: ["VITE_GEMINI_API_KEY"]
  args:
    - build
    - -t
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$SHORT_SHA
    - --build-arg
    - VITE_GEMINI_API_KEY=$(VITE_GEMINI_API_KEY)
    - .

- name: gcr.io/cloud-builders/docker
  args: ["push", "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$SHORT_SHA"]

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    - run
    - deploy
    - ${_IMAGE_NAME}
    - --image
    - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$SHORT_SHA
    - --region
    - ${_REGION}
    - --allow-unauthenticated
