substitutions:
  _REGION: "us-south1"
  _REPO: "cloud-run-source-deploy"
  _IMAGE_NAME: "meowtion-sensor"
  _SERVICE: "meowtion-sensor"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: make-env
    entrypoint: bash
    args:
      - -ceu
      - |
        : "${PROJECT_ID:?PROJECT_ID not set}"
        GEMINI=$(gcloud secrets versions access latest --secret=VITE_GEMINI_API_KEY)
        AUTH0_DOMAIN=$(gcloud secrets versions access latest --secret=VITE_AUTH0_DOMAIN)
        AUTH0_CLIENT_ID=$(gcloud secrets versions access latest --secret=VITE_AUTH0_CLIENT_ID)
        mkdir -p src
        {
          echo "VITE_GEMINI_API_KEY=$GEMINI"
          echo "VITE_AUTH0_DOMAIN=$AUTH0_DOMAIN"
          echo "VITE_AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID"
        } > src/.env

  - name: gcr.io/cloud-builders/docker
    id: docker-build
    dir: src
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$BUILD_ID
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:latest
      - .

  - name: gcr.io/cloud-builders/docker
    id: push-tags
    args:
      - sh
      - -ceu
      - |
        docker push ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$BUILD_ID
        docker push ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:latest

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$BUILD_ID
      - --region
      - ${_REGION}
      - --allow-unauthenticated

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:$BUILD_ID
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_IMAGE_NAME}:latest
